### ISSUE TITLE
Disable check for dependabot PRs

### ISSUE THREAD

**Issue by eccles** [JJ/github-pr-contains-action#101]
We use this action to ensure a link is present in an issue on Azure. However dependabot Prs will not be associated with any ticket so it would be nice if we could set 'dependabot: false' and the check will always pas for depndabot PRs.

**Comment by JJ** [comment]
Right, it's very annoying when that happens. Maybe even just make that the default.

**Comment by eccles** [comment]
that would also be a good solution. Many thanks for your attention to this..

**Comment by JJ** [comment]
Can you please check `releases/v11` Just changing the tag should work out of the box; then if you have some outstanding dependabot PR issue a `@dependabot rebase` or `recreate` to check that it does not fail now.
