### ISSUE TITLE
DiffDoesNotContain requeired

### ISSUE THREAD

**Issue by ssfxate** [JJ/github-pr-contains-action#59]
Hey, thank you for the great GH Action.
Could you please suggest for me how to do a case when I'm looking throughout the diff for not containing some words?

Kind of forgotten "debugger" and other dev things.

**Comment by JJ** [comment]
Shouldn't be too difficult to implement. I would happily accept a PR with this, or let me check and will try to implement it soonish if not very difficult. Thanks for the report anyway.

**Comment by ssfxate** [comment]
I'm not so condfident in programming to do this by myself and make a PR.

I would be really happy If you implement it. Thank you.
