### ISSUE TITLE
Error: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by vreddy96** [JJ/github-pr-contains-action#63]
name: "Check PR for word - v2"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR for iexact
      uses: JJ/github-pr-contains-action@releases/v2
      with:
        github-token: ${{github.token}}
        bodyContains: 'iexact'
        bodyDoesNotContain: ''
        diffContains: ''
        filesChanged: 1
        linesChanged: 1

I am using the above shown yaml file for the action. But I am still getting indexOf error. Any leads? @JJ

**Comment by lsmonzon** [comment]
News for this bug

**Comment by JJ** [comment]
Sorry for not having attended this before. This usually happens when the body of the PR is empty. I can try and fix that bug, or just make it more informative.
